name: Call a reusable workflow

on:
  push:
    branches: master

jobs:
  call-workflow-test:
    permissions:
      contents: read
      pull-requests: write
    uses: abc-def/example-repo/.github/workflows/workflow-test.yaml@master
